/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Control.Ccargo;
import Modelo.Mcargo;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo Caconda
 */
public class cargo extends javax.swing.JFrame {

    /**
     * Creates new form cargo
     */
    public cargo() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagem/medalha1.png")));
        setBackground(new Color(0, 0, 0));
        tbcargo.getTableHeader().setBackground(new Color(32, 136, 203));
        tbcargo.getTableHeader().setOpaque(true);
        tbcargo.getTableHeader().setFont(new Font("Yes I Can", Font.BOLD, 12));
        tbcargo.getTableHeader().setForeground(new Color(0, 0, 0));
        tbcargo.setRowHeight(25);
        listardados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbvoltar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtnome = new rojeru_san.RSMTextFull();
        btnguardar = new rojeru_san.RSButtonRiple();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcargo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cargo.png"))); // NOI18N
        jLabel1.setText("Cargo");

        lbvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/voltar.png"))); // NOI18N
        lbvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbvoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbvoltar)
                .addGap(412, 412, 412)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbvoltar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        txtnome.setPlaceholder("Escrever");
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        tbcargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbcargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcargo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbvoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbvoltarMouseClicked
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbvoltarMouseClicked

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (id == 0) {
                guardar();

            } else {
                atualizar();
                btnguardar.setText("Guardar");
            }
            listardados();

        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:

        if (id == 0) {
            guardar();

        } else {
            atualizar();
            btnguardar.setText("Guardar");
        }
        listardados();
    }//GEN-LAST:event_btnguardarActionPerformed
    private void tbcargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcargoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            Object[] option = {"Apagar", "Cancelar", "Editar"};// derclaramos um vetor objecto por onde estara escrito o que desejamos no botao JOptionPane
            int valor = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[1]);
            //OPTION[1] É PARA FOCAR NO BOTÃO CANCELAR
            if (valor == 0) {
                apagar();
                listardados();
            } else {
                if (valor == 2) {

                    id = (int) tbcargo.getValueAt(tbcargo.getSelectedRow(), 0);
                    txtnome.setText((String) tbcargo.getValueAt(tbcargo.getSelectedRow(), 1));
                    btnguardar.setText("Actualizar");
                }

            }
        }

    }//GEN-LAST:event_tbcargoMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbvoltar;
    private javax.swing.JTable tbcargo;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    // End of variables declaration//GEN-END:variables
int id = 0;

    private void atualizar() {
        Mcargo modal = new Mcargo();//instanciamos a classe modal do cargo
        String nome = txtnome.getText();//atribuimos o valor na variavel nome
        if (!nome.isEmpty()) {
            Ccargo control = new Ccargo();//instanciamos a classe control do cargo

            modal.setNomeC(nome);
            modal.setIdCargo(id);
            control.atualizar(modal);// recuperar na control
        } else {
            modal.mensagem("Prencha todos os campos");
        }
        txtnome.requestFocus();
        txtnome.setText("");
    }

    private void guardar() {
        Mcargo modal = new Mcargo();//instanciamos a classe modal do cargo
        String nome = txtnome.getText();//atribuimos o valor na variavel nome
        if (!nome.isEmpty()) {
            Ccargo control = new Ccargo();//instanciamos a classe control do cargo
            modal.setNomeC(nome);
            control.salvar(modal);// recuperar na control
        } else {
            modal.mensagem("Prencha todos os campos");
        }
        txtnome.requestFocus();
        txtnome.setText("");
    }

    private void listardados() {
        Ccargo c = new Ccargo();// instanciamos a classe control do cargo
        DefaultTableModel dtm = (DefaultTableModel) tbcargo.getModel();//instanciamos a classe default Table Model 
        Object[] dados = {"CODIGO", "CARGO"};// declaramos um vector Objecto para mostar na tabela
        dtm.setColumnIdentifiers(dados);// add na coluna
        dtm.setNumRows(0);// removemos as linhas até 0

//condicão aprimorado, for que nos permite apresentar os dados na base de dados na tabela
        for (Mcargo m : c.consulta()) {
            Object[] da = {m.getIdCargo(), m.getNomeC()};// declaramos um vector Objecto para mostar na tabela
            dtm.addRow(da);//adicionamos na linha da tabela
        }

    }

    private void apagar() {
        int n = (int) tbcargo.getValueAt(tbcargo.getSelectedRow(), 0);// declaramos uma variavel inteiro que vai receber a linha da tabela selecionada
        Mcargo m = new Mcargo();//instanciamos a classe modal do cargo
        m.setIdCargo(n);
        Ccargo ende = new Ccargo();//instanciamos a classe control do cargo
        ende.apagar(m);

    }

    private void pesquisar(String pesquisar) {
        Ccargo c = new Ccargo();// instanciamos a classe control do cargo
        DefaultTableModel dtm = (DefaultTableModel) tbcargo.getModel();//instanciamos a classe default Table Model 
        Object[] dados = {"CODIGO", "CARGO"};// declaramos um vector Objecto para mostar na tabela
        dtm.setColumnIdentifiers(dados);// add na coluna
        dtm.setNumRows(0);// removemos as linhas até 0

//condicão aprimorado, for que nos permite apresentar os dados na base de dados na tabela
        for (Mcargo m : c.pesquisar(pesquisar)) {
            Object[] da = {m.getIdCargo(), m.getNomeC()};// declaramos um vector Objecto para mostar na tabela
            dtm.addRow(da);//adicionamos na linha da tabela
        }

    }
}
