/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Control.Ccategoria;
import Control.Cdesmobilizado;
import Control.Cendereco;
import Modelo.MVdesmobilizado;
import Modelo.Mcategoria;
import Modelo.Mdesmobilizado;
import Modelo.Mendereco;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DOMINGOS FERNANDO
 */
public class Desmobilizado extends javax.swing.JFrame {

    /**
     * Creates new form Departamento
     */
    String id;
    int cont = 0;

    public Desmobilizado() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagem/medalha1.png")));
        listar();
        categoria();
        endereco();
        setBackground(new Color(0, 0, 0, 0));
        tbdesmobilizado.getTableHeader().setFont(new Font("Yes I Can", Font.BOLD, 12));
        tbdesmobilizado.getTableHeader().setOpaque(true);
        tbdesmobilizado.getTableHeader().setBackground(new Color(36, 136, 203));
        tbdesmobilizado.getTableHeader().setForeground(new Color(0, 0, 0));
        tbdesmobilizado.setRowHeight(25);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtnome = new rojeru_san.RSMTextFull();
        txtbi = new rojeru_san.RSMTextFull();
        cbendereco = new javax.swing.JComboBox();
        cbgenero = new javax.swing.JComboBox();
        btnsalvar = new rojeru_san.RSButtonRiple();
        cbcategoria = new javax.swing.JComboBox();
        txtdata = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsalario = new rojeru_san.RSMTextFull();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdesmobilizado = new javax.swing.JTable();
        txtpesquisar = new rojeru_san.RSMTextFull();
        btnprova = new rojeru_san.RSButtonRiple();
        btnimprimirTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/desmobilizado.png"))); // NOI18N
        jLabel1.setText("Desmobilizado");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/voltar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtnome.setPlaceholder("Nome");
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        txtbi.setPlaceholder("Numero do BI");
        txtbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbiKeyPressed(evt);
            }
        });

        cbendereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbendereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleciona o Endereço" }));
        cbendereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbenderecoKeyPressed(evt);
            }
        });

        cbgenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleciona o Genero", "Masculino", "Femenino" }));
        cbgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbgeneroKeyPressed(evt);
            }
        });

        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnsalvar.setText("Guardar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        cbcategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbcategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleciona a Categoria" }));
        cbcategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbcategoriaKeyPressed(evt);
            }
        });

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdataMouseClicked(evt);
            }
        });
        txtdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdataKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Data de Nascimento");

        txtsalario.setPlaceholder("Salário");
        txtsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsalarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(txtbi, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(cbendereco, 0, 453, Short.MAX_VALUE)
                    .addComponent(txtsalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbgenero, 0, 250, Short.MAX_VALUE)
                        .addComponent(txtdata)
                        .addComponent(cbcategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastramento", jPanel3);

        tbdesmobilizado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdesmobilizado.setFocusable(false);
        tbdesmobilizado.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbdesmobilizado.setRowHeight(25);
        tbdesmobilizado.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbdesmobilizado.setShowVerticalLines(false);
        tbdesmobilizado.getTableHeader().setReorderingAllowed(false);
        tbdesmobilizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdesmobilizadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdesmobilizado);

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        btnprova.setText("Prova de Vida");
        btnprova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprovaActionPerformed(evt);
            }
        });

        btnimprimirTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnimprimirTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IMPRIMIR.png"))); // NOI18N
        btnimprimirTodo.setText("IMPRIMIR TUDO");
        btnimprimirTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnprova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnimprimirTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimirTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnprova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int v = 0;
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        if (v == 0) {
            salvar();
        } else {
            cont = 1;
            btnsalvar.setText("Actualizar");
        }
        listar();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdataMouseClicked
        data();
    }//GEN-LAST:event_txtdataMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tbdesmobilizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdesmobilizadoMouseClicked
        // TODO add your handling code here:
        id = (String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 0);
        if (evt.getClickCount() == 2) {
            Object[] recebe = {"Apagar", "Cancelar", "Editar", "Imprimir"};//declaramos uma vetor objecto que vai armazenar os itens selecionado
            int n = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, recebe, recebe[1]);
            if (n == 0) {
                apagar();
                listar();
            } else {
                if (n == 2) {
                    txtnome.setText((String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 1));
                    txtbi.setText((String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 4));
                    txtsalario.setText((String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 7));
                    cont = 1;
                    btnsalvar.setText("Actualizar");
                }
                if (n == 3) {
                    Cdesmobilizado f = new Cdesmobilizado();
                    f.imprimir1(id + "");
                }
            }
        }
    }//GEN-LAST:event_tbdesmobilizadoMouseClicked

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        if (evt.getKeyCode() == 10) {
            cbgenero.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void cbgeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbgeneroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtbi.requestFocus();
        }
    }//GEN-LAST:event_cbgeneroKeyPressed

    private void txtbiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtdata.requestFocus();
        }
    }//GEN-LAST:event_txtbiKeyPressed

    private void txtdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdataKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cbendereco.requestFocus();
        }
    }//GEN-LAST:event_txtdataKeyPressed

    private void cbenderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbenderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cbcategoria.requestFocus();
        }
    }//GEN-LAST:event_cbenderecoKeyPressed

    private void cbcategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcategoriaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtsalario.requestFocus();
        }
    }//GEN-LAST:event_cbcategoriaKeyPressed

    private void btnprovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprovaActionPerformed
        // TODO add your handling code here:
        if (tbdesmobilizado.getSelectedRow() < 0) {
            btnprova.setEnabled(true);
        } else {
            btnprova.setEnabled(false);
            id = (String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 0);
            String valor = (String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 1);
            ProvaVida n = new ProvaVida(Integer.valueOf(id), valor);
            n.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnprovaActionPerformed

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void txtsalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            salvar();
        }
        listar();
    }//GEN-LAST:event_txtsalarioKeyPressed

    private void btnimprimirTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirTodoActionPerformed
        // TODO add your handling code here:
        Cdesmobilizado cd = new Cdesmobilizado();
        cd.imprimirtudo();
    }//GEN-LAST:event_btnimprimirTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desmobilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desmobilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desmobilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desmobilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desmobilizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimirTodo;
    private rojeru_san.RSButtonRiple btnprova;
    private rojeru_san.RSButtonRiple btnsalvar;
    private javax.swing.JComboBox cbcategoria;
    private javax.swing.JComboBox cbendereco;
    private javax.swing.JComboBox cbgenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbdesmobilizado;
    private rojeru_san.RSMTextFull txtbi;
    private javax.swing.JFormattedTextField txtdata;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMTextFull txtsalario;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Mdesmobilizado model = new Mdesmobilizado();//instanciamos a classe modal
//declaramos as variavel do tipo  de dado String
        String nome = txtnome.getText();//a variavel nome vai receber um valor 
        String sexo = (String) cbgenero.getSelectedItem();
        String bi = txtbi.getText();
        String nascimento = txtdata.getText();
        String salario = txtsalario.getText();
        btnprova.setEnabled(false);
        //condição que permite se foi digitado um valor
        if (!nome.isEmpty() && !sexo.isEmpty() && !nascimento.isEmpty() && !salario.isEmpty()) {
            Cdesmobilizado control = new Cdesmobilizado();//instanciamos a classe control
            model.setNome(nome);
            model.setGenero(sexo);
            model.setSalario(salario);
            model.setBi(bi);
            model.setDataNascimento(nascimento);
            model.setDatac(data());
            model.setCategoria((Mcategoria) cbcategoria.getSelectedItem());
            model.setEndereco((Mendereco) cbendereco.getSelectedItem());
            if (cont == 0) {
                control.salvar(model);
            } else {
                model.setIdMobilizado(Integer.valueOf(id));
                control.atualizar(model);
            }
        } else {
            model.mensagem("Prencha os campos");
        }
        txtnome.requestFocus();
        txtnome.setText("");
        txtbi.setText("");
        txtsalario.setText("");
        txtdata.setText("");
        cbgenero.setSelectedIndex(0);
        cbendereco.setSelectedIndex(0);
        cbcategoria.setSelectedIndex(0);
    }

    private void categoria() {

        Control.Ccategoria c = new Ccategoria();// instanciamos a control

        for (Mcategoria item : c.consulta()) {
            cbcategoria.addItem(item);//add na combox os itens cadastrado no formulario categoria
        }
    }

    private void endereco() {
        Control.Cendereco c = new Cendereco();// instanciamos a control

        for (Mendereco item : c.listar()) {
            cbendereco.addItem(item);//add na combox os itens cadastrado no formulario categoria
        }

    }

    private String data() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy/MM/dd");
        String dt = s.format(d);
        txtdata.setText(dt);
        return dt;
    }

    private void listar() {
        Cdesmobilizado cd = new Cdesmobilizado();// instanciar a control 
        DefaultTableModel dtm = (DefaultTableModel) tbdesmobilizado.getModel();//instanciamos a classe default
        Object[] dados = {"CODIGO", "NOME", "GENERO", "NASCIMENTO", "Nº BI", "DATA DO CADASTRO", "CATEGORIA",
            "SALÁRIO", "MUNICIPIO", "PROVINCIA"};//declaramos um objecto que vai mostrar os titulos na tabela
        dtm.setColumnIdentifiers(dados);//adicionamos na tabela
        dtm.setNumRows(0);//limpamos na tabela caso tenha um item
        for (MVdesmobilizado md : cd.consultar()) {
            Object[] recebe = {md.getIdMobilizado(), md.getNome(), md.getGenero(),
                md.getDataNascimento(), md.getBi(), md.getDataCadastro(), md.getCategoria(), md.getSalario() + "  KZ ", md.getMunicipio(), md.getProvincia()};
            dtm.addRow(recebe);
        }
    }

    private void apagar() {
        Mdesmobilizado md = new Mdesmobilizado();//instanciamos a modal
        String valor = (String) tbdesmobilizado.getValueAt(tbdesmobilizado.getSelectedRow(), 0);//declaramos uma variavel que recebe a um valor da tabela caso seja seleciona e é convertido
        md.setIdMobilizado(Integer.valueOf(valor));
        Cdesmobilizado cd = new Cdesmobilizado();//instanciamos a control
        cd.delete(md);//chamamos o medoto delete que esta na control desmobilizado
    }

    private void pesquisar(String p) {
        Cdesmobilizado d = new Cdesmobilizado();
        DefaultTableModel dtm = (DefaultTableModel) tbdesmobilizado.getModel();
        Object[] dados = {"CODIGO", "NOME", "GENERO", "NASCIMENTO", "Nº BI", "DATA DO CADASTRO", "CATEGORIA",
            "SALÁRIO", "MUNICIPIO", "PROVINCIA"};//declaramos um objecto que vai mostrar os titulos na tabela
        dtm.setColumnIdentifiers(dados);//adicionamos na tabela
        dtm.setNumRows(0);//limpamos na tabela caso tenha um item
        for (MVdesmobilizado md : d.pesquisar(p)) {
            Object[] recebe = {md.getIdMobilizado(), md.getNome(), md.getGenero(),
                md.getDataNascimento(), md.getBi(), md.getDataCadastro(), md.getCategoria(), md.getSalario() + "  KZ", md.getMunicipio(), md.getProvincia()};
            dtm.addRow(recebe);

        }

    }
}
