/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Control.Cendereco;
import Modelo.Mendereco;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DOMINGOS FERNANDO
 */
public class endereco extends javax.swing.JFrame {

    /**
     * Creates new form Departamento
     */
    public endereco() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagem/medalha1.png")));
        setBackground(new Color(0, 0, 0, 0));
        tbEndereco.getTableHeader().setFont(new Font("Sogoi UI", Font.BOLD, 12));
        tbEndereco.getTableHeader().setOpaque(true);
        tbEndereco.getTableHeader().setBackground(new Color(36, 136, 203));
        tbEndereco.getTableHeader().setForeground(new Color(0, 0, 0));
        tbEndereco.setRowHeight(25);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtprovincia = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEndereco = new javax.swing.JTable();
        txtpesquisar = new rojeru_san.RSMTextFull();
        btnsalvar = new rojeru_san.RSButtonRiple();
        txtcidade = new rojeru_san.RSMTextFull();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/endereco.png"))); // NOI18N
        jLabel1.setText("Endereço");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/voltar.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(274, 274, 274)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)))
        );

        txtprovincia.setPlaceholder("Provincia");
        txtprovincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprovinciaKeyPressed(evt);
            }
        });

        tbEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEndereco.setFocusable(false);
        tbEndereco.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbEndereco.setRowHeight(25);
        tbEndereco.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbEndereco.setShowVerticalLines(false);
        tbEndereco.getTableHeader().setReorderingAllowed(false);
        tbEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEnderecoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEndereco);

        txtpesquisar.setPlaceholder("Pesquisar.");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnsalvar.setText("Guardar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        txtcidade.setPlaceholder("Cidade");
        txtcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcidadeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(txtprovincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        if (id == 0) {
            salvar();
        } else {
            atualizar();
            btnsalvar.setText("Actualizar");
        }
        listar();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtcidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtprovincia.requestFocus();
        }
    }//GEN-LAST:event_txtcidadeKeyPressed
    int id = 0;
    private void txtprovinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprovinciaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (id == 0) {
                salvar();

            } else {
                atualizar();
                btnsalvar.setText("Guardar");
            }
            listar();

        }
    }//GEN-LAST:event_txtprovinciaKeyPressed
    UIManager ui;
    private void tbEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEnderecoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            ui = null;
            UIManager.put("OptionPane.background", new Color(36, 136, 203));// para por cor do fundo do JOptionPane
            UIManager.put("Panel.background", new Color(36, 136, 203));
            Object[] option = {"Apagar", "Cancelar", "Editar"};// derclaramos um vetor objecto por onde estara escrito o que desejamos no botao JOptionPane
            int valor = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[1]);
            //OPTION[1] É PARA FOCAR NO BOTÃO CANCELAR
            if (valor == 0) {
                eliminar();
                listar();
            } else {
                if (valor == 2) {
                    id = (int) tbEndereco.getValueAt(tbEndereco.getSelectedRow(), 0);
                    txtcidade.setText((String) tbEndereco.getValueAt(tbEndereco.getSelectedRow(), 1));
                    txtprovincia.setText((String) tbEndereco.getValueAt(tbEndereco.getSelectedRow(), 2));
                    btnsalvar.setText("Actualizar");
                }

            }
        }
    }//GEN-LAST:event_tbEnderecoMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new endereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEndereco;
    private rojeru_san.RSMTextFull txtcidade;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMTextFull txtprovincia;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        String cidade = txtcidade.getText();
        String provincia = txtprovincia.getText();
        Mendereco model = new Mendereco();
        Cendereco control = new Cendereco();
        if (!cidade.isEmpty() && !provincia.isEmpty()) {
            model.setCidade(cidade);
            model.setProvincia(provincia);
            control.salvar(model);
        } else {
            model.mensagem("Prencha os campos");
        }
        txtcidade.requestFocus();
        txtcidade.setText("");
        txtprovincia.setText("");
    }

    private void listar() {
        Cendereco c = new Cendereco();
        DefaultTableModel dtm = (DefaultTableModel) tbEndereco.getModel();

        Object[] titulo = {"Codigo", "Cidade", "Provinçia"};
        dtm.setColumnIdentifiers(titulo);
        dtm.setNumRows(0);
        for (Mendereco item : c.listar()) {
            Object[] dado = {item.getIdEndereco(), item.getCidade(), item.getProvincia()};
            dtm.addRow(dado);
        }
    }

    private void eliminar() {
        int n = (int) tbEndereco.getValueAt(tbEndereco.getSelectedRow(), 0);
        Mendereco m = new Mendereco();
        m.setIdEndereco(n);
        Cendereco ende = new Cendereco();
        ende.apagar(m);

    }

    private void atualizar() {
        String cidade = txtcidade.getText();
        String provincia = txtprovincia.getText();
        Mendereco model = new Mendereco();
        Cendereco control = new Cendereco();
        if (!cidade.isEmpty() && !provincia.isEmpty()) {
            model.setCidade(cidade);
            model.setIdEndereco(id);
            model.setProvincia(provincia);
            control.atualizar(model);
            txtcidade.requestFocus();
            txtcidade.setText("");
            txtprovincia.setText("");
        } else {
            model.mensagem("Prencha os campos");
        }

    }

    private void pesquisar(String pesquisar) {
        Cendereco c = new Cendereco();
        DefaultTableModel dtm = (DefaultTableModel) tbEndereco.getModel();

        Object[] titulo = {"Codigo", "Cidade", "Provinçia"};
        dtm.setColumnIdentifiers(titulo);
        dtm.setNumRows(0);
        for (Mendereco item : c.pesquisar(pesquisar)) {
            Object[] dado = {item.getIdEndereco(), item.getCidade(), item.getProvincia()};
            dtm.addRow(dado);
        }
    }
}
