/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Control.Cdesmobilizado;
import Control.Clogin;
import Control.Cprova;
import Control.Ctarefa;
import Modelo.MVconsulta;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo Caconda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Princial
     */
    //CONSTRUTUOR
    public Principal() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagem/medalha1.png")));
        Control.Clogin l = new Clogin();//INSTANCIAMOS A CLASSE CONTROL DA LOGIN NO CONSTRUTOR
        lbnome.setText(l.recuprarValor(1));//RECUPERAMOS O VALOR DA LOGIN FUNCIONARIO
        contarDesmobilizado();
        desmobilizadomorto();
        horadata();// CHAMAMOS A CLASSE DATE
        this.setExtendedState(Principal.MAXIMIZED_BOTH);// CODIGO PARA A MAXIMIZACAO DA TELA
        listar();//LISTAR OS DADOS NA TELA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lbMaximizar = new javax.swing.JLabel();
        lbMinimizar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        btndesmobilizado = new rojeru_san.RSButtonRiple();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        rSButtonRiple4 = new rojeru_san.RSButtonRiple();
        btncargo = new rojeru_san.RSButtonRiple();
        rSButtonRiple6 = new rojeru_san.RSButtonRiple();
        BTNFUNCIONARIO = new rojeru_san.RSButtonRiple();
        btnprova_vida = new rojeru_san.RSButtonRiple();
        jPanel4 = new javax.swing.JPanel();
        lbvida = new javax.swing.JLabel();
        lbdesmobilizado = new javax.swing.JLabel();
        lbvivo = new javax.swing.JLabel();
        lbterminar = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtudo = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbdatahora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fechar.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        lbMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Maximizar.png"))); // NOI18N
        lbMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMaximizarMouseClicked(evt);
            }
        });

        lbMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Minimizar.png"))); // NOI18N
        lbMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMaximizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechar)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMinimizar)
                    .addComponent(lbMaximizar)
                    .addComponent(lblFechar))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/configuracao.png"))); // NOI18N
        jLabel2.setText("Config");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/ajuda.png"))); // NOI18N
        jLabel7.setText("Ajuda");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rSButtonRiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/departamento1.png"))); // NOI18N
        rSButtonRiple2.setText("  Departamento");
        rSButtonRiple2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonRiple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple2ActionPerformed(evt);
            }
        });

        btndesmobilizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/desmobilizado.png"))); // NOI18N
        btndesmobilizado.setText("  Desmobilizado");
        btndesmobilizado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndesmobilizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesmobilizadoActionPerformed(evt);
            }
        });

        rSButtonRiple3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/endereco.png"))); // NOI18N
        rSButtonRiple3.setText(" Endereço");
        rSButtonRiple3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonRiple3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple3ActionPerformed(evt);
            }
        });

        rSButtonRiple4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/tarefa1.png"))); // NOI18N
        rSButtonRiple4.setText("Tarefa");
        rSButtonRiple4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonRiple4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple4ActionPerformed(evt);
            }
        });

        btncargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cargo.png"))); // NOI18N
        btncargo.setText("  Cargo");
        btncargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargoActionPerformed(evt);
            }
        });

        rSButtonRiple6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/categoria1.png"))); // NOI18N
        rSButtonRiple6.setText("    Categoria");
        rSButtonRiple6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonRiple6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple6ActionPerformed(evt);
            }
        });

        BTNFUNCIONARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/funcionario.png"))); // NOI18N
        BTNFUNCIONARIO.setText("  Funcionário");
        BTNFUNCIONARIO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNFUNCIONARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFUNCIONARIOActionPerformed(evt);
            }
        });

        btnprova_vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/heart.png"))); // NOI18N
        btnprova_vida.setText("Prova de Vida");
        btnprova_vida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprova_vidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNFUNCIONARIO, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(btndesmobilizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnprova_vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btncargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonRiple2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonRiple6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonRiple3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonRiple4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(BTNFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndesmobilizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprova_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncargo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonRiple2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonRiple6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonRiple3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonRiple4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbvida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbvida.setForeground(new java.awt.Color(51, 102, 255));
        lbvida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/coracao.png"))); // NOI18N
        lbvida.setText("Prova de Vida");
        lbvida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbvidaMouseClicked(evt);
            }
        });

        lbdesmobilizado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbdesmobilizado.setForeground(new java.awt.Color(51, 102, 255));
        lbdesmobilizado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbdesmobilizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/medalha1.png"))); // NOI18N
        lbdesmobilizado.setText("Desmobilizado");
        lbdesmobilizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdesmobilizadoMouseClicked(evt);
            }
        });

        lbvivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbvivo.setForeground(new java.awt.Color(51, 102, 255));
        lbvivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/medalha1.png"))); // NOI18N
        lbvivo.setText("Desmobilizado ");
        lbvivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbvivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbvida, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbvivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbdesmobilizado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbvida)
                    .addComponent(lbdesmobilizado)
                    .addComponent(lbvivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbterminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbterminar.setForeground(new java.awt.Color(51, 102, 255));
        lbterminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbterminar.setText("Terminar Sessão");
        lbterminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbterminarMouseClicked(evt);
            }
        });

        lbnome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tbtudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbtudo);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/login.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Eventos");

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/realizar.png"))); // NOI18N
        jLabel5.setText("Tarefas Realizadas");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/todos.png"))); // NOI18N
        jLabel8.setText("Atualização dos Desmobilizados");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        lbdatahora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbdatahora.setText("Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbterminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbnome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdatahora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbnome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbterminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(lbdatahora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndesmobilizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesmobilizadoActionPerformed
        // TODO add your handling code here:
        new Desmobilizado().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btndesmobilizadoActionPerformed

    private void rSButtonRiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple2ActionPerformed
        // TODO add your handling code here:
        new Departamento().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_rSButtonRiple2ActionPerformed

    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
        // TODO add your handling code here:
        new endereco().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    private void rSButtonRiple4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple4ActionPerformed
        // TODO add your handling code here:
        new tarefa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonRiple4ActionPerformed

    private void btncargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargoActionPerformed
        // TODO add your handling code here:
        new cargo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncargoActionPerformed

    private void rSButtonRiple6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple6ActionPerformed
        // TODO add your handling code here:
        new categoria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonRiple6ActionPerformed

    private void lbterminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbterminarMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbterminarMouseClicked

    private void BTNFUNCIONARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFUNCIONARIOActionPerformed
        // TODO add your handling code here:
        new funcionario().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BTNFUNCIONARIOActionPerformed

    private void btnprova_vidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprova_vidaActionPerformed
        // TODO add your handling code here:
        new ProvaVida().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnprova_vidaActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        tarefa();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisarKeyPressed

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        listarpesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void lbMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Principal.ICONIFIED);
    }//GEN-LAST:event_lbMinimizarMouseClicked

    private void lbMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMaximizarMouseClicked
        // TODO add your handling code here:
        // codigo para maximizar a tela

        if (this.getExtendedState() != Principal.MAXIMIZED_BOTH) {
            this.setExtendedState(Principal.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(Principal.NORMAL);
        }
    }//GEN-LAST:event_lbMaximizarMouseClicked

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lbvidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbvidaMouseClicked
        // TODO add your handling code here:
//        Cprova p = new Cprova();
//         p.imprimirtudo();
    }//GEN-LAST:event_lbvidaMouseClicked

    private void lbdesmobilizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdesmobilizadoMouseClicked
        // TODO add your handling code here:
//        Cdesmobilizado d= new Cdesmobilizado();
//        d.imprimirtudo();
    }//GEN-LAST:event_lbdesmobilizadoMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Ajuda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lbvivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbvivoMouseClicked
        // TODO add your handling code here:
        desmobilizadomorto();
    }//GEN-LAST:event_lbvivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void horadata() {

        Timer t = new Timer();//instanciar o tempo
        t.schedule(new TimerTask() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy  |  'São:'HH:mm:ss");
                lbdatahora.setText(s.format(d));
            }
        }, 0, 100);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple BTNFUNCIONARIO;
    private rojeru_san.RSButtonRiple btncargo;
    private rojeru_san.RSButtonRiple btndesmobilizado;
    private rojeru_san.RSButtonRiple btnprova_vida;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaximizar;
    private javax.swing.JLabel lbMinimizar;
    private javax.swing.JLabel lbdatahora;
    private javax.swing.JLabel lbdesmobilizado;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbterminar;
    private javax.swing.JLabel lbvida;
    private javax.swing.JLabel lbvivo;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    private rojeru_san.RSButtonRiple rSButtonRiple4;
    private rojeru_san.RSButtonRiple rSButtonRiple6;
    private javax.swing.JTable tbtudo;
    private rojeru_san.RSMTextFull txtpesquisar;
    // End of variables declaration//GEN-END:variables
    private void listar() {
        int valor = 0;

        Cprova p = new Cprova();

        DefaultTableModel dt = (DefaultTableModel) tbtudo.getModel();
        Object recebe[] = {"CODIGO", "DESMOBILIZADO", "GENERO", "ESTADO", "NASCIMENTO",
            "DATA DO CADASTRO", "CATEGORIA", "SALÁRIO", "MUNICIPIO", "PROVINCIA"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (MVconsulta modelo : p.consultaV()) {
            if (!modelo.getEstado().equalsIgnoreCase("morto")) {
                valor++;
                Object[] dad = {modelo.getCodigo(), modelo.getDesmobilizado(), modelo.getGenero(), modelo.getEstado(),
                    modelo.getData(), modelo.getDatacadastro(), modelo.getCategoria(), modelo.getSalario() + " KZ", modelo.getProvincia(),
                    modelo.getCidade()};
                dt.addRow(dad);
            }

        }
        lbvida.setText("Prova de Vida  " + valor);

    }

    private void listarpesquisar(String pesquisar) {
        Cprova p = new Cprova();
        DefaultTableModel dt = (DefaultTableModel) tbtudo.getModel();
        Object recebe[] = {"CODIGO", "DESMOBILIZADO", "GENERO", "VALOR A RECEBER", "CATEGORIA",
            "PROVINCIA", "CIDADE", "ESTADO", "PROVA DE VIDA", "DATA"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (MVconsulta modelo : p.pesquisar(pesquisar)) {
            Object[] dad = {
                modelo.getCodigo(),
                modelo.getDesmobilizado(), modelo.getGenero(), modelo.getSalario(),
                modelo.getCategoria(), modelo.getProvincia(), modelo.getCidade(), modelo.getEstado(), modelo.getData(), modelo.getDatacadastro()};
            dt.addRow(dad);

        }

    }

    private void contarDesmobilizado() {
        int n = 0;
        Cdesmobilizado cd = new Cdesmobilizado();// instanciar a control 

        for (Modelo.MVdesmobilizado md : cd.consultar()) {
            n++;
        }
        lbdesmobilizado.setText("Desmobilizado : " + n);
    }

    private void tarefa() {

        Ctarefa t = new Ctarefa();
        DefaultTableModel tb = (DefaultTableModel) tbtudo.getModel();
        Object[] dados = {"CODIGO", "TAREFA", "DATA DO INICIO", "DATA DO TERMINO", "ESTADO DA TAREFA", "DESCRIÇÃO", "DEPARTAMENTO"};
        tb.setColumnIdentifiers(dados);
        tb.setNumRows(0);
        for (Modelo.MVTAREFA item : t.listar()) {
            Object[] dad = {item.getCODIGO(), item.getNomeDaTarefa(), item.getInicio(), item.getTermino(),
                item.getEstado(), item.getDescricao(), item.getDepartamento()};
            tb.addRow(dad);
        }

    }

    private void desmobilizadomorto() {
        int morto = 0;
        Cprova p = new Cprova();
        DefaultTableModel dt = (DefaultTableModel) tbtudo.getModel();
        Object recebe[] = {"CODIGO", "DESMOBILIZADO", "GENERO", "VALOR A RECEBER", "CATEGORIA",
            "PROVINCIA", "CIDADE", "ESTADO", "PROVA DE VIDA", "DATA"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (MVconsulta modelo : p.consultaV()) {
            if (modelo.getEstado().equalsIgnoreCase("morto")) {
                morto++;
                Object[] dad = {
                    modelo.getCodigo(),
                    modelo.getDesmobilizado(), modelo.getGenero(), modelo.getSalario(),
                    modelo.getCategoria(), modelo.getProvincia(), modelo.getCidade(), modelo.getEstado(), modelo.getData(), modelo.getDatacadastro()};
                dt.addRow(dad);
            }
        }
        lbvivo.setText("Desmobilizado Morto : " + morto);
    }

    
}