/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Control.Cdepartamento;
import Control.Ctarefa;
import Modelo.Mdepartamento;
import Modelo.Mtarefa;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DOMINGOS FERNANDO
 */
public class tarefa extends javax.swing.JFrame {

    /**
     * Creates new form Departamento
     */
    public tarefa() {
        initComponents();
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagem/medalha1.png")));
        setBackground(new Color(0, 0, 0, 0));
        tbtarefa.getTableHeader().setBackground(new Color(36, 136, 203));
        tbtarefa.getTableHeader().setFont(new Font("Yes I Can ", Font.BOLD, 12));
        tbtarefa.getTableHeader().setOpaque(true);
        tbtarefa.getTableHeader().setForeground(new Color(0, 0, 0));
        tbtarefa.setRowHeight(25);
        departamento();
        listartarefa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txttarefa = new rojeru_san.RSMTextFull();
        btnsalvar = new rojeru_san.RSButtonRiple();
        cbdepartamento = new javax.swing.JComboBox();
        txtdatainicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdatatermino = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescricao = new javax.swing.JTextArea();
        cbestado = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtarefa = new javax.swing.JTable();
        txtpesquisar = new rojeru_san.RSMTextFull();
        btnimprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/tarefa1.png"))); // NOI18N
        jLabel1.setText("Agendar Tarefa");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/voltar.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(266, 266, 266)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txttarefa.setPlaceholder("Tarefa");
        txttarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttarefaKeyPressed(evt);
            }
        });

        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnsalvar.setText("Guardar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        cbdepartamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbdepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleciona o Departamento" }));

        try {
            txtdatainicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatainicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatainicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdatainicioMouseClicked(evt);
            }
        });
        txtdatainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatainicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Descrição");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data do  Termino");

        try {
            txtdatatermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatatermino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatatermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdataterminoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdataterminoMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Data do  Inicio");

        txtdescricao.setColumns(20);
        txtdescricao.setRows(5);
        txtdescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdescricaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtdescricao);

        cbestado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o estado da tarefa", "Por Fazer", "Fazendo", "Feito" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbdepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 167, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbestado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtdatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdatatermino, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdatatermino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(txttarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastramento", jPanel3);

        tbtarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtarefa.setFocusable(false);
        tbtarefa.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbtarefa.setRowHeight(25);
        tbtarefa.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbtarefa.setShowVerticalLines(false);
        tbtarefa.getTableHeader().setReorderingAllowed(false);
        tbtarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtarefaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtarefa);

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        btnimprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IMPRIMIR.png"))); // NOI18N
        btnimprimir.setText("IMPRIMIR TUDO");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnimprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtdescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdescricaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescricaoMouseClicked

    private void txtdataterminoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdataterminoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataterminoMousePressed

    private void txtdataterminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdataterminoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataterminoMouseClicked

    private void txtdatainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatainicioActionPerformed

    private void txtdatainicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdatainicioMouseClicked
        // TODO add your handling code here:
        datadosistema();
    }//GEN-LAST:event_txtdatainicioMouseClicked

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        if (id == 0) {
            salvar();
        } else {
            atualizar();
            btnsalvar.setText("Actualizar");
        }
        listartarefa();
    }//GEN-LAST:event_btnsalvarActionPerformed
    int id = 0;

    private void tbtarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtarefaMouseClicked
        // TODO add your handling code here:
        id = (int) tbtarefa.getValueAt(tbtarefa.getSelectedRow(), 0);
        if (evt.getClickCount() == 2) {
            Object[] option = {"Apagar", "Cancelar", "Editar","imprimir"};// derclaramos um vetor objecto por onde estara escrito o que desejamos no botao JOptionPane
            int valor = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[1]);
            //OPTION[1] É PARA FOCAR NO BOTÃO CANCELAR
            if (valor == 0) {
                apagar();
                listartarefa();
            } else {
                if (valor == 2) {
                    txttarefa.setText((String) tbtarefa.getValueAt(tbtarefa.getSelectedRow(), 1));
                    txtdatainicio.setText((String) tbtarefa.getValueAt(tbtarefa.getSelectedRow(), 2));
                    txtdatatermino.setText((String) tbtarefa.getValueAt(tbtarefa.getSelectedRow(), 3));
                    txtdescricao.setText((String) tbtarefa.getValueAt(tbtarefa.getSelectedRow(), 5));
                    btnsalvar.setText("Actualizar");
                }
                if (valor == 3) {
                    Ctarefa d = new Ctarefa();
                    d.imprimir(id + "");
                }
            }
        }
    }//GEN-LAST:event_tbtarefaMouseClicked

    private void txttarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttarefaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtdatainicio.requestFocus();
        }
    }//GEN-LAST:event_txttarefaKeyPressed

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
        Ctarefa t= new Ctarefa();
        t.imprimirtudo();
    }//GEN-LAST:event_btnimprimirActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private rojeru_san.RSButtonRiple btnsalvar;
    private javax.swing.JComboBox cbdepartamento;
    private javax.swing.JComboBox cbestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbtarefa;
    private javax.swing.JFormattedTextField txtdatainicio;
    private javax.swing.JFormattedTextField txtdatatermino;
    private javax.swing.JTextArea txtdescricao;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMTextFull txttarefa;
    // End of variables declaration//GEN-END:variables

    private void departamento() {
        Cdepartamento c = new Cdepartamento();
        for (Mdepartamento m : c.listar()) {
            cbdepartamento.addItem(m);
        }
    }

    private void listartarefa() {
        Ctarefa t = new Ctarefa();
        DefaultTableModel tb = (DefaultTableModel) tbtarefa.getModel();
        Object[] dados = {"CODIGO", "TAREFA", "DATA DO INICIO", "DATA DO TERMINO", "ESTADO DA TAREFA", "DESCRIÇÃO","DEPARTAMENTO"};
        tb.setColumnIdentifiers(dados);
        tb.setNumRows(0);
        for (Modelo.MVTAREFA item : t.listar()) {
            Object[] dad = {item.getCODIGO(), item.getNomeDaTarefa(), item.getInicio(), item.getTermino(),
                item.getEstado(), item.getDescricao(),item.getDepartamento()};
            tb.addRow(dad);
        }

    }

    private void salvar() {
        if (txttarefa.getText().equals("") | txtdescricao.getText().equals("")
                | txtdatainicio.getText().equals("     /  /  ")
                | txtdatatermino.getText().equals("     /  /  ")
                | cbdepartamento.getSelectedIndex() == 0 | cbestado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Preenche todos os campos");

        } else {
            String tarefa, datainicio, datatermino, descricao, estado;
            estado = (String) cbestado.getSelectedItem();

            tarefa = txttarefa.getText();
            descricao = txtdescricao.getText();
            datainicio = txtdatainicio.getText();
            datatermino = txtdatatermino.getText();

            Mtarefa m = new Mtarefa();

            Control.Ctarefa c = new Ctarefa();
            m.setIdTarefa(id);
            m.setNomeDaTarefa(tarefa);
            m.setDataInicio(datainicio);
            m.setDataTermino(datatermino);
            m.setDescricao(descricao);
            m.setEstado(estado);
            m.setDepartamento((Mdepartamento) cbdepartamento.getSelectedItem());
            c.salvar(m);

        }
    }

    void datadosistema() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy/MM/");
        String data = s.format(d);
        txtdatainicio.setText(data);
        txtdatatermino.setText(data);

    }

    private void apagar() {

        int id = (int) tbtarefa.getValueAt(tbtarefa.getSelectedRow(), 0);
        Mtarefa m = new Mtarefa();
        m.setIdTarefa(id);
        Control.Ctarefa c = new Ctarefa();
        c.deletar(m);
    }

    private void atualizar() {
        String tarefa, datainicio, datatermino, descricao, estado;
        tarefa = txttarefa.getText();
        datainicio = txtdatainicio.getText();
        datatermino = txtdatatermino.getText();
        descricao = txtdescricao.getText();
        estado = (String) cbestado.getSelectedItem();
        Mtarefa model = new Mtarefa();
        Ctarefa control = new Ctarefa();
        if (!tarefa.isEmpty() && !datainicio.isEmpty() && !datatermino.isEmpty() && !descricao.isEmpty()) {
            Mtarefa m = new Mtarefa();

            Control.Ctarefa c = new Ctarefa();
            m.setIdTarefa(id);
            m.setNomeDaTarefa(tarefa);
            m.setDataInicio(datainicio);
            m.setDataTermino(datatermino);
            m.setDescricao(descricao);
            m.setEstado(estado);
            m.setDepartamento((Mdepartamento) cbdepartamento.getSelectedItem());
            c.atualizar(m);
        } else {
            model.mensagem("Prencha os campos");
        }

    }

    private void pesquisar(String pesquisar) {
        Ctarefa ct = new Ctarefa();
        DefaultTableModel dtm = (DefaultTableModel) tbtarefa.getModel();
       Object[] dados = {"CODIGO", "TAREFA", "DATA DO INICIO", "DATA DO TERMINO", "ESTADO DA TAREFA", "DESCRIÇÃO","DEPARTAMENTO"};
        dtm.setColumnIdentifiers(dados);
        dtm.setNumRows(0);
        for (Modelo.MVTAREFA item : ct.pesquisar(pesquisar)) {
            Object[] dad = {item.getCODIGO(), item.getNomeDaTarefa(), item.getInicio(), item.getTermino(),
                item.getEstado(), item.getDescricao(),item.getDepartamento()};
            dtm.addRow(dad);
        }

    }
}
